version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    revive:
      rules:
        - name: function-length
          arguments:
            - 30
            - 0
        - name: var-naming
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
