name: Publish Package

on:
  release:
    types: [published]
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-binaries:
    name: Publish Binaries as Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ "$VERSION" != v* ]]; then
            VERSION="dev-${GITHUB_SHA::8}"
          fi
          go build -ldflags "-s -w -X github.com/JayDubyaEey/yeet/pkg/version.Version=${VERSION}" \
            -o yeet-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} \
            ./cmd

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: yeet-${{ matrix.os }}-${{ matrix.arch }}
          path: yeet-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          retention-days: 30

  create-release-bundle:
    name: Create Release Bundle
    runs-on: ubuntu-latest
    needs: publish-binaries
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: yeet-*
          merge-multiple: true
          path: ./binaries

      - name: Create checksums
        working-directory: ./binaries
        run: |
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: yeet-all-platforms
          path: ./binaries/*
          retention-days: 30
